//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleServiceRef
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VehicleDTO", Namespace="http://schemas.datacontract.org/2004/07/VehicleRental.Contracts.DTOs")]
    public partial class VehicleDTO : object
    {
        
        private string BrandField;
        
        private bool IsAvailableField;
        
        private string LicensePlateField;
        
        private string ModelField;
        
        private decimal PricePerDayField;
        
        private int VehicleIdField;
        
        private int YearField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Brand
        {
            get
            {
                return this.BrandField;
            }
            set
            {
                this.BrandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAvailable
        {
            get
            {
                return this.IsAvailableField;
            }
            set
            {
                this.IsAvailableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicensePlate
        {
            get
            {
                return this.LicensePlateField;
            }
            set
            {
                this.LicensePlateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Model
        {
            get
            {
                return this.ModelField;
            }
            set
            {
                this.ModelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PricePerDay
        {
            get
            {
                return this.PricePerDayField;
            }
            set
            {
                this.PricePerDayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VehicleId
        {
            get
            {
                return this.VehicleIdField;
            }
            set
            {
                this.VehicleIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Year
        {
            get
            {
                return this.YearField;
            }
            set
            {
                this.YearField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VehicleServiceRef.IVehicleService")]
    public interface IVehicleService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/GetAllVehicles", ReplyAction="http://tempuri.org/IVehicleService/GetAllVehiclesResponse")]
        System.Threading.Tasks.Task<VehicleServiceRef.VehicleDTO[]> GetAllVehiclesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/GetAvailableVehicles", ReplyAction="http://tempuri.org/IVehicleService/GetAvailableVehiclesResponse")]
        System.Threading.Tasks.Task<VehicleServiceRef.VehicleDTO[]> GetAvailableVehiclesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/GetVehicleById", ReplyAction="http://tempuri.org/IVehicleService/GetVehicleByIdResponse")]
        System.Threading.Tasks.Task<VehicleServiceRef.VehicleDTO> GetVehicleByIdAsync(int vehicleId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IVehicleServiceChannel : VehicleServiceRef.IVehicleService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class VehicleServiceClient : System.ServiceModel.ClientBase<VehicleServiceRef.IVehicleService>, VehicleServiceRef.IVehicleService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public VehicleServiceClient() : 
                base(VehicleServiceClient.GetDefaultBinding(), VehicleServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IVehicleService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VehicleServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(VehicleServiceClient.GetBindingForEndpoint(endpointConfiguration), VehicleServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VehicleServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(VehicleServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VehicleServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(VehicleServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public VehicleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<VehicleServiceRef.VehicleDTO[]> GetAllVehiclesAsync()
        {
            return base.Channel.GetAllVehiclesAsync();
        }
        
        public System.Threading.Tasks.Task<VehicleServiceRef.VehicleDTO[]> GetAvailableVehiclesAsync()
        {
            return base.Channel.GetAvailableVehiclesAsync();
        }
        
        public System.Threading.Tasks.Task<VehicleServiceRef.VehicleDTO> GetVehicleByIdAsync(int vehicleId)
        {
            return base.Channel.GetVehicleByIdAsync(vehicleId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVehicleService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IVehicleService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:61525/VehicleService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return VehicleServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IVehicleService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return VehicleServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IVehicleService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IVehicleService,
        }
    }
}
