//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRental.WinClient.VehicleServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VehicleServiceRef.IVehicleService")]
    public interface IVehicleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/GetAllVehicles", ReplyAction="http://tempuri.org/IVehicleService/GetAllVehiclesResponse")]
        VehicleRental.Contracts.DTOs.VehicleDTO[] GetAllVehicles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/GetAllVehicles", ReplyAction="http://tempuri.org/IVehicleService/GetAllVehiclesResponse")]
        System.Threading.Tasks.Task<VehicleRental.Contracts.DTOs.VehicleDTO[]> GetAllVehiclesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/GetAvailableVehicles", ReplyAction="http://tempuri.org/IVehicleService/GetAvailableVehiclesResponse")]
        VehicleRental.Contracts.DTOs.VehicleDTO[] GetAvailableVehicles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/GetAvailableVehicles", ReplyAction="http://tempuri.org/IVehicleService/GetAvailableVehiclesResponse")]
        System.Threading.Tasks.Task<VehicleRental.Contracts.DTOs.VehicleDTO[]> GetAvailableVehiclesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/GetVehicleById", ReplyAction="http://tempuri.org/IVehicleService/GetVehicleByIdResponse")]
        VehicleRental.Contracts.DTOs.VehicleDTO GetVehicleById(int vehicleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVehicleService/GetVehicleById", ReplyAction="http://tempuri.org/IVehicleService/GetVehicleByIdResponse")]
        System.Threading.Tasks.Task<VehicleRental.Contracts.DTOs.VehicleDTO> GetVehicleByIdAsync(int vehicleId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVehicleServiceChannel : VehicleRental.WinClient.VehicleServiceRef.IVehicleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VehicleServiceClient : System.ServiceModel.ClientBase<VehicleRental.WinClient.VehicleServiceRef.IVehicleService>, VehicleRental.WinClient.VehicleServiceRef.IVehicleService {
        
        public VehicleServiceClient() {
        }
        
        public VehicleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VehicleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VehicleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public VehicleRental.Contracts.DTOs.VehicleDTO[] GetAllVehicles() {
            return base.Channel.GetAllVehicles();
        }
        
        public System.Threading.Tasks.Task<VehicleRental.Contracts.DTOs.VehicleDTO[]> GetAllVehiclesAsync() {
            return base.Channel.GetAllVehiclesAsync();
        }
        
        public VehicleRental.Contracts.DTOs.VehicleDTO[] GetAvailableVehicles() {
            return base.Channel.GetAvailableVehicles();
        }
        
        public System.Threading.Tasks.Task<VehicleRental.Contracts.DTOs.VehicleDTO[]> GetAvailableVehiclesAsync() {
            return base.Channel.GetAvailableVehiclesAsync();
        }
        
        public VehicleRental.Contracts.DTOs.VehicleDTO GetVehicleById(int vehicleId) {
            return base.Channel.GetVehicleById(vehicleId);
        }
        
        public System.Threading.Tasks.Task<VehicleRental.Contracts.DTOs.VehicleDTO> GetVehicleByIdAsync(int vehicleId) {
            return base.Channel.GetVehicleByIdAsync(vehicleId);
        }
    }
}
