//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleRental.Client.ReservationServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReservationServiceRef.IReservationService")]
    public interface IReservationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/BookVehicle", ReplyAction="http://tempuri.org/IReservationService/BookVehicleResponse")]
        bool BookVehicle(int userId, int vehicleId, System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/BookVehicle", ReplyAction="http://tempuri.org/IReservationService/BookVehicleResponse")]
        System.Threading.Tasks.Task<bool> BookVehicleAsync(int userId, int vehicleId, System.DateTime startDate, System.DateTime endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/CancelReservation", ReplyAction="http://tempuri.org/IReservationService/CancelReservationResponse")]
        bool CancelReservation(int reservationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/CancelReservation", ReplyAction="http://tempuri.org/IReservationService/CancelReservationResponse")]
        System.Threading.Tasks.Task<bool> CancelReservationAsync(int reservationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GetUserReservations", ReplyAction="http://tempuri.org/IReservationService/GetUserReservationsResponse")]
        VehicleRental.Contracts.DTOs.ReservationDTO[] GetUserReservations(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/GetUserReservations", ReplyAction="http://tempuri.org/IReservationService/GetUserReservationsResponse")]
        System.Threading.Tasks.Task<VehicleRental.Contracts.DTOs.ReservationDTO[]> GetUserReservationsAsync(int userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservationServiceChannel : VehicleRental.Client.ReservationServiceRef.IReservationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservationServiceClient : System.ServiceModel.ClientBase<VehicleRental.Client.ReservationServiceRef.IReservationService>, VehicleRental.Client.ReservationServiceRef.IReservationService {
        
        public ReservationServiceClient() {
        }
        
        public ReservationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool BookVehicle(int userId, int vehicleId, System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.BookVehicle(userId, vehicleId, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<bool> BookVehicleAsync(int userId, int vehicleId, System.DateTime startDate, System.DateTime endDate) {
            return base.Channel.BookVehicleAsync(userId, vehicleId, startDate, endDate);
        }
        
        public bool CancelReservation(int reservationId) {
            return base.Channel.CancelReservation(reservationId);
        }
        
        public System.Threading.Tasks.Task<bool> CancelReservationAsync(int reservationId) {
            return base.Channel.CancelReservationAsync(reservationId);
        }
        
        public VehicleRental.Contracts.DTOs.ReservationDTO[] GetUserReservations(int userId) {
            return base.Channel.GetUserReservations(userId);
        }
        
        public System.Threading.Tasks.Task<VehicleRental.Contracts.DTOs.ReservationDTO[]> GetUserReservationsAsync(int userId) {
            return base.Channel.GetUserReservationsAsync(userId);
        }
    }
}
